/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SwapIQ.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(38a3f44a9f24c287566dc0c6dbd011e1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <correctiq/SwapIQ.h>
// pydoc.h is automatically generated in the build directory
#include <SwapIQ_pydoc.h>

void bind_SwapIQ(py::module& m)
{

    using SwapIQ    = ::gr::correctiq::SwapIQ;


    py::class_<SwapIQ, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<SwapIQ>>(m, "SwapIQ", D(SwapIQ))

        .def(py::init(&SwapIQ::make),
           py::arg("datatype"),
           py::arg("datasize"),
           D(SwapIQ,make)
        )
        



        ;




}








